### ISSUE TITLE
Python files recognized as Dockerfile

### ISSUE THREAD

**Issue by NotSqrt** [asbjornenge/Docker.tmbundle#26]
Hello,

The following line makes python files starting with `from package import module` match the `first_line_match` pattern :
https://github.com/asbjornenge/Docker.tmbundle/blob/master/Syntaxes/Dockerfile.sublime-syntax#L8

Maybe add something along the line of : `(?!(.*?\simport\s))` ?

Thanks !

**Comment by blag** [comment]
Fixed in #25.

**Comment by lethosor** [comment]
Was this ever released? Still seeing this behavior in v1.5.1 (at least that's the version Sublime reports)

**Comment by tvalimaki** [comment]
@blag, @princemaple : This fix hasn't been released yet. The release notes of v1.5.1 suggest that the python issue is fixed, but the two commits that fix it are not part of the release.

**Comment by blag** [comment]
@tvalimaki I just created release `1.5.2` on GitHub that includes #25. From what I've read, that should be picked up by Sublime's Package Control automatically. If it isn't picked up automatically after about 24 hours, please let me know.

**Comment by tvalimaki** [comment]
Thanks, it's on PackageControl now and python files are no longer confused as Dockerfile.
